# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

recombine <- function(strand1, strand2, cross) {
    .Call(`_ibdsim2_recombine`, strand1, strand2, cross)
}

